### ISSUE TITLE
Feature Request: Double Click to Open

### ISSUE THREAD

**Issue by Mave95** [equeim/tremotesf2#128]
It would be nice to have a double click to open on finished torrents. That way you don't have to right click and select open each time. On transgui this is the default behavior. If you don't want to have this as a default an option for this would also be nice.

**Comment by thany** [comment]
Just so you know, this would also involve some configuration: a translation of the paths used on the server, into something the client can access. It's very unlikely to be the exact same path, but rather a network path of some sort.

On my configuration, the paths for complete and incomplete torrents are completely different. A different server even. But on the transmission server, it's just `/download/incomplete` and `/download/complete`. Heck, it doesn't even know about where files physically go, it being a docker image and all.

**Comment by Mave95** [comment]
The configuration option to map the remote path to a local path already exists under Tools -> Connection Settings. I just need an option to select the double click action to open.
In docker you could additionally mount `/download/incomplete` and `/download/complete` to a path on the docker host and mount these directories to your local machine via nfs, sshfs or samba.

**Comment by thany** [comment]
Does it? Oops 😀

Oh I see! There's is a bloody scrollbar in the settings dialog for a connection. That is weird. It didn't stand out to me *at all* because the dialog seemed to naturally "end", i.e. no half-visible element. That might have triggered wanting to scroll.

But honestly, this is better solved with tabs. In a regular application, scrolling through something other than a list of something, is weird. Especially in a dialog that is specially designed to hold its own contents.

**Comment by mcdemon05** [comment]
Please add double click to open in new realease! :)
It's very good feature in transgui, but I can't use transgui because too much problems.
