### ISSUE TITLE
Can this be used on macOS?

### ISSUE THREAD

**Issue by faergeek** [equeim/tremotesf2#18]
I'm not sure if it can run on macOS if there's nothing have been done for it. And I don't see any mention of macOS in README. Was it somehow compiled/tested on macOS? Or if it wasn't, is there any chance to see macOS version in the near future?

**Comment by equeim** [comment]
Theoretically it is possible to compile Tremotesf for macOS, although is would likely require some small fixes here and there. I, however, do not own any Apple PCs (and don't plan to) and thus can't build it on macOS (theoretically it is possible to install macOS in VM, but XCode requires Apple registration, if I'm not mistaken).

**Comment by tabell** [comment]
Just wanted to comment that I was able to build successfully for macos 12.6.3 (intel macbook pro). I had to tweak a few cmake files, and there are a few minor UI glitches, but otherwise it works surprisingly well. I installed qt and kde using Craft into my user dir.

I was able to add a server, with https, connect, add a torrent, etc.
