### ISSUE TITLE
Install and build fails on debian 12

### ISSUE THREAD

**Issue by midzer** [equeim/tremotesf2#274]
Hi,

this looks like a promising application!

Miserably, I can't get it to install on debian 12 (bookworm) which ships `libfmt9`.
Could not compile from source either with build instructions.

If you give me some guidelines, I can dig deeper.

Have a nice weekend
midzer

**Comment by equeim** [comment]
I tried to build tremotesf in debian:bookworm container and it succeeded. Can you provide build log and commands that you used to build it?

**Comment by midzer** [comment]
First, I've installed tremotesf2 via `apt` and it complains about missing dependency `libfmt7` which does not exist on debian 12 any more.

**Comment by equeim** [comment]
Ah, so you tried to install it from http://download.opensuse.org/repositories/home:/equeim:/tremotesf/Debian_11/ repository? That's only for Debian 11. Different Debian versions are not compatible with each other, packages from 11 can't be installed on 12 (sometimes apt can allow it but it's still not recommended). Since 12 is not released yet I don't provide a repository for it. You will need to build Tremotesf from source code or install it from Flatpak.

**Comment by equeim** [comment]
I added Debian Testing repo to OBS. Same instructions as in README, just replace `Debian_11` with `Debian_Testing`.
