### ISSUE TITLE
Flatpak. Switch to dark theme with latest qt6 version

### ISSUE THREAD

**Issue by SoiledBrush** [equeim/tremotesf2#395]
Till the release of 2.5.0 I was using tremotesf with QT_STYLE_OVERRIDE=kvantum to make it match with libadwaita. With the latest update I got error 
`QApplication: invalid style override 'kvantum' passed, ignoring it.
	Available styles: Breeze, Windows, Fusion`
Is there any way to at least switch app to breeze-dark theme through flatpak env variables? QT_STYLE_OVERRIDE=breeze-dark or QT_QPA_PLATFORMTHEME=breeze-dark didn't work

**Comment by equeim** [comment]
That's probably because I switched to 5.15-23.08 version of KDE runtime and kvantum should be rebuilt for that too. I suggest making PR to its repository: https://github.com/flathub/org.kde.KStyle.Kvantum, like this one - https://github.com/flathub/org.kde.KStyle.Kvantum/pull/15. You can build and install it locally in the mean time.

Unfortunately there is no way to override Breeze color scheme AFAIK, it always uses system one (probably some hardcoded one in case of GNOME).

**Comment by SoiledBrush** [comment]
Thanks, I managed to build it for myself.
![Screenshot from 2023-10-20 20-19-44](https://github.com/equeim/tremotesf2/assets/43366389/f1c6cff0-23ea-4727-9db5-7d455999f745)
