### ISSUE TITLE
[Feature Request] Ability to delete historical download paths (just like Tremotesf for Android)

### ISSUE THREAD

**Issue by chuwza** [equeim/tremotesf2#430]
Hi, Tremotesf for Android is able to delete download paths that have been used before (I delete these download paths because: some are no longer used, some are no longer valid)

As the picture shows, Tremotesf (Android) is able to delete these paths, hopefully Tremotesf2 for Windows will add this important feature.
![IMG_20231210_104130](https://github.com/equeim/tremotesf2/assets/30049891/6bcb4db1-0982-4eb5-aba0-bbcb7e7f63f8)

Currently Tremotesf2 for Windows can delete paths with the delete key, but this is only an illusion, when I make a new download the old paths are still there!

So I would really like Tremotesf2 for Windows to have this feature!
![IMG_20231210_104101](https://github.com/equeim/tremotesf2/assets/30049891/89f74eab-f135-4919-99be-d1fc827881d2)

**Comment by equeim** [comment]
Currently the logic is that removal of paths is saved only when "OK" is pressed (i.e. torrent is added), so that user can still cancel it by closing the dialog. Also, the list always contains all download directories of currently existing torrents. So if you remove a directory which some other torrent is already using it will still appear in the list later (changing this would be impractical because it will require to maintain permanent blacklist of directories, and it's unclear how user will be able to un-remove a directory from it).

Does this not work for you?

**Comment by chuwza** [comment]
> Currently the logic is that removal of paths is saved only when "OK" is pressed (i.e. torrent is added), so that user can still cancel it by closing the dialog. Also, the list always contains all download directories of currently existing torrents. So if you remove a directory which some other torrent is already using it will still appear in the list later (changing this would be impractical because it will require to maintain permanent blacklist of directories, and it's unclear how user will be able to un-remove a directory from it).
> 
> Does this not work for you?

Okay, I understand. This worked, thank you very much!
