### ISSUE TITLE
Excessive file system permissions?

### ISSUE THREAD

**Issue by moonraker2** [equeim/tremotesf2#545]
Debian software center reports the flatpak tremotesf2 as needing read-access to all files.
How is this necessary?
Another Transmission remote app, transmission-remote-gtk, is able to make do with access to just two areas of the file system, instead of "everything".

**Comment by equeim** [comment]
> Debian software center reports the flatpak tremotesf2 as needing read-access to all files.
> How is this necessary?
> Another Transmission remote app, transmission-remote-gtk, is able to make do with access to just two areas of the file system, instead of "everything".
> 

It is needed to be able to open torrents (i.e. their downloaded files) from Tremotesf. You can download torrents anywhere, and Flatpak has a very annoying restriction: even though you can request OS to open a file through the portal, this only works for files the app *already has access to* (which is dumb since portal implementation can just ask the user for permission).

IIRC there is a portal API to request access to a specific directory but this will be annoying to users (it works through a directory chooser dialog) and would require me to add quite a lot of Flatpak-specific code which I really don't want to do.

Alternatively I can restrict access to ~/Downloads but that of course would mean that opening torrents downloaded elsewhere won't work.

The current solution just works and requires minimal effort from me which is the way I like it.

**Comment by moonraker2** [comment]
Ok, thanks for taking the time to explain.

Would you then recommend going for the deb-version instead- or maybe that's more a matter of personal preference?

**Comment by equeim** [comment]
> Ok, thanks for taking the time to explain.
> 
> Would you then recommend going for the deb-version instead- or maybe that's more a matter of personal preference?

For Debian and Ubuntu flatpak is better, especially if you use Wayland. Deb version is built with Qt 5 since necessary dependencies were added to Debian only recently and still don't exist in stable versions of distros. Flatpak uses Qt 6.

Functionality-wise there shouldn't be any differences.
